/**
 * Central numeric tuning for matching scores, boosts, and routing thresholds.
 */

export const SCORE_BOOSTS = {
  calculateScore: {
    EXACT_OR_PHRASE_BASE: 3,
    FULL_MATCH_BASE: 2,
    PARTIAL_BASE: 1,
    CONTROLLED_TYPO: 0.5,
    VOWEL_DROP_SHORTHAND: 0.4,
    LENGTH_WEIGHT_DIVISOR: 10,
    SHORT_STANDALONE_KEYWORD_MAX_LEN: 4,
    PHRASE_COVERAGE_MIN_MATCHED_PARTS: 2,
    PHRASE_COVERAGE_MIN_STRONG_PARTS: 1,
    PHRASE_NEAR_COMPLETE_MIN_STRONG_PARTS: 2,
    PHRASE_COVERAGE_STRONG_BONUS: 0.4,
    HAS_PART_SIMILARITY_STRICT_PART_LEN: 4,
    HAS_PART_SIMILARITY_STRICT_TOKEN_LEN: 3,
  },
  intent: {
    MULTI_WORD_PHRASE_MATCH_EXTRA: 2,
    /** Scores at or above this are treated as "strong" keyword hits (aligns with full-match base). */
    STRONG_KEYWORD_SCORE_MIN: 2,
    MULTI_KEYWORD_EVIDENCE_BONUS: 1,
    MULTI_KEYWORD_EVIDENCE_MIN_MATCHES: 2,
    SHORT_UTTERANCE_MAX_TOKENS: 4,
    SHORT_UTTERANCE_MATCHED_TOKEN_OVERLAP_BONUS: 0.6,
    SHORT_UTTERANCE_MIN_MATCHED_TOKENS: 2,
    WEAK_MATCH_CLUSTER_MIN: 2,
    WEAK_MATCH_CLUSTER_BONUS: 0.35,
    CASUAL_CONVERSATION_PATTERN_BONUS: 0.7,
    CASUAL_PATTERN_MIN_MATCHED_TOKENS: 1,
    HOW_ARE_YOU_MOOD_PATTERN_BOOST: 2.1,
    WHAT_DOING_SMALL_TALK_PATTERN_BOOST: 2.1,
    ARE_YOU_MOOD_PATTERN_BOOST: 1.2,
    SHORT_SOFT_ANCHOR_BONUS: 0.35,
    MIN_STRONG_MATCHES_FOR_SHORT_SOFT: 1,
    /** Prefer small_talk over greeting when within this score delta. */
    SMALL_TALK_VS_GREETING_SCORE_MARGIN: 1.2,
    DOMINANCE_NEAR_TIE_MARGIN: 0.8,
    DOMINANCE_MIN_MATCHED_TOKENS: 2,
    DOMINANCE_OPPONENT_MAX_MATCHED_TOKENS: 1,
    MIN_ACCEPT_INTENT_SCORE: 1,
    CLARIFY_RUNNER_UP_GAP_MAX: 1,
    CLARIFY_BEST_SCORE_CEILING: 5,
    /** Clarify when the longest matched keyword is shorter than this (ambiguous short cues). */
    CLARIFY_LONGEST_KEYWORD_LEN_LT: 8,
    CLARIFY_MIN_INPUT_TOKEN_COUNT: 2,
    ALLOW_SHORT_STRONG_UTTERANCE_MAX_TOKENS: 3,
    MIN_SCORING_TOKENS_FOR_SHORT_SOFT: 2,
  },
  validation: {
    MIN_MATCHED_TOKENS_DOMINANCE: 2,
    MIN_INPUT_TOKENS_FOR_WEAK_CONTEXT_GATE: 2,
    MIN_KEYWORD_MATCHES_FOR_MULTI_TOKEN_CONFIDENCE: 2,
    MIN_MATCHED_TOKENS_FOR_MULTI_TOKEN_CONFIDENCE: 2,
  },
  knowledge: {
    PHRASE_SUBSTRING_SIGNAL_BONUS: 1,
    QUESTION_WORD_PRIORITY_BONUS: 2,
    MIN_RETURN_SCORE: 1,
    PHRASE_HEAD_TAIL_SLICE_LEN: 3,
  },
  routing: {
    KNOWLEDGE_ELIGIBLE_MIN_SCORE: 2,
    FORCE_INTENT_MIN_SCORE: 5,
    FORCE_INTENT_MIN_KEYWORD_MATCHES: 2,
  },
};
